---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie-service
  labels:
    app: {{ include "fastapiapp.name" . }}
    component: movie-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapiapp.name" . }}
      component: movie-service
  template:
    metadata:
      labels:
        app: {{ include "fastapiapp.name" . }}
        component: movie-service
    spec:
      containers:
        - name: movie-service
          image: "{{ .Values.movie_service.image.repository }}:{{ .Values.movie_service.image.tag }}"
          imagePullPolicy: {{ .Values.movie_service.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.movie_service.service.targetPort }}
          env:
            - name: DATABASE_URI
              value: "{{ .Values.movie_service.env.DATABASE_URI }}"
            - name: CAST_SERVICE_HOST_URL
              value: "{{ .Values.movie_service.env.CAST_SERVICE_HOST_URL }}"
          resources:
            {{- toYaml .Values.movie_service.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast-service
  labels:
    app: {{ include "fastapiapp.name" . }}
    component: cast-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapiapp.name" . }}
      component: cast-service
  template:
    metadata:
      labels:
        app: {{ include "fastapiapp.name" . }}
        component: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.cast_service.image.repository }}:{{ .Values.cast_service.image.tag }}"
          imagePullPolicy: {{ .Values.cast_service.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.cast_service.service.targetPort }}
          env:
            - name: DATABASE_URI
              value: "{{ .Values.cast_service.env.DATABASE_URI }}"
          resources:
            {{- toYaml .Values.cast_service.resources | nindent 12 }}
