replicaCount: 3

movie_service:
  image:
    repository: dimitri15/movie_service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30001
    targetPort: 8000
  env:
    DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
    CAST_SERVICE_HOST_URL: "http://cast_service:8000/api/v1/casts/"
  resources: {}
  autoscaling:
    enabled: false

cast_service:
  image:
    repository: dimitri15/cast_service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30002
    targetPort: 8000
  env:
    DATABASE_URI: "postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev"
  resources: {}
  autoscaling:
    enabled: false

postgres_movie:
  image: postgres:12.1-alpine
  persistence:
    enabled: true
    size: 10Gi
  env:
    POSTGRES_USER: movie_db_username
    POSTGRES_PASSWORD: movie_db_password
    POSTGRES_DB: movie_db_dev

postgres_cast:
  image: postgres:12.1-alpine
  persistence:
    enabled: true
    size: 10Gi
  env:
    POSTGRES_USER: cast_db_username
    POSTGRES_PASSWORD: cast_db_password
    POSTGRES_DB: cast_db_dev

nginx:
  image:
    repository: nginx:latest
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
    targetPort: 8080
